apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tst-orthweb
resources:
  - namespace.yaml
  - ../base/orthanc
  - ../base/route
transformers:
  - labels.yaml
images:
- name: orthanc-plugins
  newName: jodogne/orthanc-plugins
  newTag: 1.9.7
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: orthanc-app
  data:
    db.addr: postgres-ha-postgresql-ha-pgpool.tst-orthweb.svc.cluster.local 
replicas:
- name: orthanc
  count: 3
patches:
  - target:
      kind: Gateway
      name: dcm-gw
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - dicom.tst.orthweb.com
  - target:
      kind: Gateway
      name: web-gw
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - web.tst.orthweb.com
  - target:
      kind: VirtualService 
      name: dcm-vs
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - dicom.tst.orthweb.com
  - target:
      kind: VirtualService
      name: web-vs
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - web.tst.orthweb.com
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-orthanc
    patch: |-
      - op: add
        path: /spec/rules/0/from/0/source/namespaces
        value:
        - istio-system
        - tst-orthweb 
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-orthanc 
    patch: |-
      - op: add
        path: /spec/rules/1/from/0/source/namespaces
        value: 
        - istio-system
        - tst-orthweb
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-postgres 
    patch: |-
      - op: add
        path: /spec/rules/0/from/0/source/namespaces
        value: 
        - tst-orthweb
